#!/usr/bin/env python3
"""
Export Random Forest Model for ESP32 Deployment

This script:
1. Trains both full (200 trees) and embedded (25 trees, depth=10) models
2. Compares accuracy on test set
3. Exports embedded model using emlearn library
4. Generates fall_model.h C header file for Arduino
"""

import os
import sys
import argparse
import numpy as np
import joblib

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from imu_fall_detection_pipeline import (
    load_all_sessions,
    make_windows,
    extract_features_for_windows,
    train_test_split_by_session,
    train_random_forest,
    train_random_forest_embedded,
    evaluate_model
)


def export_model_to_c(model, output_path: str, model_name: str = "fall_model"):
    """
    Export sklearn model to C header file using emlearn.
    
    Args:
        model: Trained sklearn model
        output_path: Path to save .h file
        model_name: Name for the model in C code
    """
    try:
        import emlearn
    except ImportError:
        print("ERROR: emlearn not installed. Run: pip install emlearn")
        print("Skipping C export.")
        return False
    
    # Convert model to C using float dtype for precision
    # int16 loses too much precision for small gyro values
    cmodel = emlearn.convert(model, method='inline', dtype='float')
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Save as C header
    cmodel.save(file=output_path, name=model_name)
    
    print(f"Model exported to: {output_path} (float dtype)")
    return True


def get_feature_names():
    """Return ordered list of feature names (must match extraction order)."""
    features = []
    
    # Acceleration features
    for col in ['ax', 'ay', 'az']:
        for stat in ['mean', 'std', 'min', 'max']:
            features.append(f'{col}_{stat}')
    
    # Acceleration magnitude
    for stat in ['mean', 'std', 'min', 'max']:
        features.append(f'a_mag_{stat}')
    
    # Gyro features
    for col in ['gx', 'gy', 'gz']:
        for stat in ['mean', 'std', 'min', 'max']:
            features.append(f'{col}_{stat}')
    
    # Gyro magnitude
    for stat in ['mean', 'std', 'min', 'max']:
        features.append(f'w_mag_{stat}')
    
    return features


def generate_feature_header(output_path: str, feature_names: list):
    """
    Generate C header file with feature extraction definitions.
    
    Args:
        output_path: Path to save features.h
        feature_names: List of feature names in order
    """
    content = """/*
 * Feature definitions for IMU fall detection
 * Auto-generated by export_model_for_esp32.py
 */

#ifndef FEATURES_H
#define FEATURES_H

// Number of features
#define N_FEATURES 32

// Feature indices (for reference)
"""
    
    for i, name in enumerate(feature_names):
        content += f"#define FEAT_{name.upper()} {i}\n"
    
    content += """
// Feature names (for debugging)
static const char* FEATURE_NAMES[N_FEATURES] = {
"""
    
    for name in feature_names:
        content += f'    "{name}",\n'
    
    content = content.rstrip(',\n') + '\n'
    content += "};\n\n"
    content += "#endif // FEATURES_H\n"
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Feature header exported to: {output_path}")


def generate_labels_header(output_path: str, labels: list):
    """
    Generate C header file with label definitions.
    
    Args:
        output_path: Path to save labels.h
        labels: List of label strings in class order
    """
    content = """/*
 * Label definitions for IMU fall detection
 * Auto-generated by export_model_for_esp32.py
 */

#ifndef LABELS_H
#define LABELS_H

// Number of classes
"""
    content += f"#define N_CLASSES {len(labels)}\n\n"
    content += "// Class indices\n"
    
    for i, label in enumerate(labels):
        content += f"#define CLASS_{label.upper()} {i}\n"
    
    content += """
// Class names
static const char* CLASS_NAMES[N_CLASSES] = {
"""
    
    for label in labels:
        content += f'    "{label}",\n'
    
    content = content.rstrip(',\n') + '\n'
    content += "};\n\n"
    
    # Add critical labels for alerting
    content += """// Critical labels that trigger alerts
// f = falling, af = after_fall_on_floor, nf = unstable_standing (near fall)
static inline bool is_critical_label(int class_idx) {
"""
    
    critical_indices = []
    for i, label in enumerate(labels):
        if label in ['f', 'af', 'nf']:
            critical_indices.append(str(i))
    
    if critical_indices:
        content += f"    return class_idx == {' || class_idx == '.join(critical_indices)};\n"
    else:
        content += "    return false;\n"
    
    content += "}\n\n"
    content += "#endif // LABELS_H\n"
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
    
    print(f"Labels header exported to: {output_path}")


def save_comparison_report(
    full_results: dict,
    embedded_results: dict,
    output_path: str,
    embedded_params: dict
):
    """
    Save model comparison report.
    
    Args:
        full_results: Evaluation results for full model
        embedded_results: Evaluation results for embedded model
        output_path: Path to save report
        embedded_params: Parameters used for embedded model
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("# ESP32 Model Comparison Report\n\n")
        f.write("Generated by `export_model_for_esp32.py`\n\n")
        
        f.write("## Model Configurations\n\n")
        f.write("| Model | Trees | Max Depth | Est. Size |\n")
        f.write("|-------|-------|-----------|----------|\n")
        f.write("| Full | 200 | Unlimited | ~1.5-2 MB |\n")
        f.write(f"| Embedded | {embedded_params['n_estimators']} | {embedded_params['max_depth']} | ~50-150 KB |\n\n")
        
        f.write("## Accuracy Comparison\n\n")
        f.write("| Model | Accuracy | Diff from Full |\n")
        f.write("|-------|----------|----------------|\n")
        full_acc = full_results['accuracy']
        embedded_acc = embedded_results['accuracy']
        diff = embedded_acc - full_acc
        f.write(f"| Full | {full_acc:.4f} ({full_acc*100:.2f}%) | - |\n")
        f.write(f"| Embedded | {embedded_acc:.4f} ({embedded_acc*100:.2f}%) | {diff:+.4f} ({diff*100:+.2f}%) |\n\n")
        
        f.write("## Per-Class F1 Scores (Embedded Model)\n\n")
        f.write("| Class | Precision | Recall | F1-Score | Support |\n")
        f.write("|-------|-----------|--------|----------|--------|\n")
        
        report = embedded_results['classification_report']
        for label in sorted(report.keys()):
            if label in ['accuracy', 'macro avg', 'weighted avg']:
                continue
            metrics = report[label]
            f.write(f"| {label} | {metrics['precision']:.3f} | {metrics['recall']:.3f} | {metrics['f1-score']:.3f} | {int(metrics['support'])} |\n")
        
        f.write("\n## Critical Labels Performance\n\n")
        f.write("These labels trigger alerts on ESP32:\n\n")
        f.write("| Label | Meaning | F1-Score |\n")
        f.write("|-------|---------|----------|\n")
        
        critical_labels = {'f': 'Falling', 'af': 'After fall on floor', 'nf': 'Unstable standing'}
        for label, meaning in critical_labels.items():
            if label in report:
                f1 = report[label]['f1-score']
                f.write(f"| {label} | {meaning} | {f1:.3f} |\n")
        
        f.write("\n## Full Classification Reports\n\n")
        
        f.write("### Full Model\n\n")
        f.write("```\n")
        f.write(full_results['classification_report_str'])
        f.write("```\n\n")
        
        f.write("### Embedded Model\n\n")
        f.write("```\n")
        f.write(embedded_results['classification_report_str'])
        f.write("```\n")
    
    print(f"Comparison report saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Export Random Forest model for ESP32")
    parser.add_argument(
        "--data-dir",
        default=None,
        help="Path to collected_data directory"
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Path to output directory for Arduino headers"
    )
    parser.add_argument(
        "--n-estimators",
        type=int,
        default=25,
        help="Number of trees for embedded model (default: 25)"
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=10,
        help="Max depth for embedded model (default: 10)"
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.3,
        help="Fraction of sessions for testing (default: 0.3)"
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed (default: 42)"
    )
    
    args = parser.parse_args()
    
    # Set default paths relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    
    data_dir = args.data_dir or os.path.join(project_root, "backend", "collected_data")
    output_dir = args.output_dir or os.path.join(project_root, "arduino", "mpu6050_ml")
    reports_dir = os.path.join(project_root, "reports")
    
    print("=" * 60)
    print("ESP32 Model Export Pipeline")
    print("=" * 60)
    print(f"\nData directory: {data_dir}")
    print(f"Output directory: {output_dir}")
    print(f"Embedded model: {args.n_estimators} trees, max_depth={args.max_depth}")
    
    # Step 1: Load and preprocess data
    print("\n[1/6] Loading data...")
    df = load_all_sessions(data_dir)
    
    print("\n[2/6] Creating windows...")
    windows_df = make_windows(df, window_size_s=1.0, window_step_s=0.5)
    
    print("\n[3/6] Extracting features...")
    features_df, X, y = extract_features_for_windows(df, windows_df)
    
    # Get feature names and class labels
    metadata_cols = ['session_id', 'window_idx', 'window_start_ms', 'window_end_ms', 'label', 'n_samples']
    feature_names = [c for c in features_df.columns if c not in metadata_cols]
    class_labels = sorted(features_df['label'].unique())
    
    print(f"\nFeatures: {len(feature_names)}")
    print(f"Classes: {class_labels}")
    
    # Step 2: Split data
    print("\n[4/6] Splitting train/test by session...")
    X_train, X_test, y_train, y_test, sessions_train, sessions_test = train_test_split_by_session(
        features_df, X, y, test_size=args.test_size, random_state=args.random_state
    )
    
    # Step 3: Train both models
    print("\n[5/6] Training models...")
    
    print("\nTraining full model (200 trees, unlimited depth)...")
    full_model = train_random_forest(X_train, y_train, random_state=args.random_state)
    
    print(f"\nTraining embedded model ({args.n_estimators} trees, max_depth={args.max_depth})...")
    embedded_model = train_random_forest_embedded(
        X_train, y_train,
        n_estimators=args.n_estimators,
        max_depth=args.max_depth,
        random_state=args.random_state
    )
    
    # Step 4: Evaluate both models
    print("\n[6/6] Evaluating models...")
    
    full_results = evaluate_model(full_model, X_test, y_test, "Full Random Forest (200 trees)")
    embedded_results = evaluate_model(embedded_model, X_test, y_test, f"Embedded Random Forest ({args.n_estimators} trees)")
    
    # Step 5: Export model to C
    print("\n" + "=" * 60)
    print("Exporting model for ESP32...")
    print("=" * 60)
    
    # Export C model header
    model_path = os.path.join(output_dir, "fall_model.h")
    export_success = export_model_to_c(embedded_model, model_path, "fall_model")
    
    # Export feature definitions
    features_path = os.path.join(output_dir, "features.h")
    generate_feature_header(features_path, feature_names)
    
    # Export label definitions
    labels_path = os.path.join(output_dir, "labels.h")
    generate_labels_header(labels_path, class_labels)
    
    # Save comparison report
    report_path = os.path.join(reports_dir, "esp32_model_comparison.md")
    embedded_params = {'n_estimators': args.n_estimators, 'max_depth': args.max_depth}
    save_comparison_report(full_results, embedded_results, report_path, embedded_params)
    
    # Save models as joblib (for future use)
    models_dir = os.path.join(project_root, "ml", "models")
    os.makedirs(models_dir, exist_ok=True)
    
    joblib.dump(full_model, os.path.join(models_dir, "full_random_forest.joblib"))
    joblib.dump(embedded_model, os.path.join(models_dir, "embedded_random_forest.joblib"))
    print(f"\nModels saved to: {models_dir}")
    
    # Summary
    print("\n" + "=" * 60)
    print("Export Complete!")
    print("=" * 60)
    print(f"\nFull model accuracy:     {full_results['accuracy']:.4f} ({full_results['accuracy']*100:.2f}%)")
    print(f"Embedded model accuracy: {embedded_results['accuracy']:.4f} ({embedded_results['accuracy']*100:.2f}%)")
    diff = embedded_results['accuracy'] - full_results['accuracy']
    print(f"Difference:              {diff:+.4f} ({diff*100:+.2f}%)")
    
    print(f"\nGenerated files:")
    print(f"  - {model_path}")
    print(f"  - {features_path}")
    print(f"  - {labels_path}")
    print(f"  - {report_path}")
    
    if not export_success:
        print("\nWARNING: emlearn not installed - model not exported to C.")
        print("Install emlearn to generate fall_model.h:")
        print("  pip install emlearn")
    
    return embedded_model, embedded_results


if __name__ == "__main__":
    main()
