/*
 * Label definitions for IMU fall detection
 * Auto-generated by train_combined_full.py
 */

#ifndef LABELS_H
#define LABELS_H

// Number of classes
#define N_CLASSES 7

// Class indices
#define CLASS_AF 0
#define CLASS_F 1
#define CLASS_NF 2
#define CLASS_R 3
#define CLASS_SI 4
#define CLASS_ST 5
#define CLASS_W 6

// Class names
static const char* CLASS_NAMES[N_CLASSES] = {
    "af",
    "f",
    "nf",
    "r",
    "si",
    "st",
    "w"
};

// Critical labels that trigger alerts
// f = falling, af = after_fall_on_floor, nf = unstable_standing (near fall)
static inline bool is_critical_label(int class_idx) {
    return class_idx == 0 || class_idx == 1 || class_idx == 2;
}

// State machine transition rules
// Rows = from state, Cols = to state
// Rules:
//   - st, si, w, r, nf can go to any state EXCEPT af
//   - f (falling) can only go to f or af
//   - af (after fall) can only go to af, si, st (recovery)
static const bool VALID_TRANSITIONS[N_CLASSES][N_CLASSES] = {
    // To:    af     f      nf     r      si     st     w
    { true , false, false, false, true , true , false }, // af: after fall: can go to af, si, st (recovery)
    { true , true , false, false, false, false, false }, // f: falling: can only go to f, af
    { false, true , true , true , true , true , true  }, // nf: unstable: can go to any EXCEPT af
    { false, true , true , true , true , true , true  }, // r: running: can go to any EXCEPT af
    { false, true , true , true , true , true , true  }, // si: sitting: can go to any EXCEPT af
    { false, true , true , true , true , true , true  }, // st: standing: can go to any EXCEPT af
    { false, true , true , true , true , true , true  }, // w: walking: can go to any EXCEPT af
};

// Check if transition from current state to new state is valid
static inline bool is_valid_transition(int from_state, int to_state) {
    if (from_state < 0 || from_state >= N_CLASSES) return true;
    if (to_state < 0 || to_state >= N_CLASSES) return false;
    return VALID_TRANSITIONS[from_state][to_state];
}

// Get valid next state (returns ml_prediction if valid, else stays in current_state)
static inline int get_valid_next_state(int current_state, int ml_prediction) {
    if (is_valid_transition(current_state, ml_prediction)) {
        return ml_prediction;
    }
    return current_state;
}

#endif // LABELS_H
