/*
 * Label definitions for IMU fall detection
 * Auto-generated by export_model_for_esp32.py
 */

#ifndef LABELS_H
#define LABELS_H

// Number of classes
#define N_CLASSES 7

// Class indices
#define CLASS_AF 0
#define CLASS_F 1
#define CLASS_NF 2
#define CLASS_R 3
#define CLASS_SI 4
#define CLASS_ST 5
#define CLASS_W 6

// Class names
static const char* CLASS_NAMES[N_CLASSES] = {
    "af",
    "f",
    "nf",
    "r",
    "si",
    "st",
    "w"
};

// Critical labels that trigger alerts
// f = falling, af = after_fall_on_floor, nf = unstable_standing (near fall)
static inline bool is_critical_label(int class_idx) {
    return class_idx == 0 || class_idx == 1 || class_idx == 2;
}

// ============================================================================
// State Machine Transition Rules
// ============================================================================
// Defines valid transitions between activity states to reduce false predictions
//
// Transition matrix: VALID_TRANSITIONS[current_state][next_state] = true/false
//
// Rules:
//   st, si, w, r, nf -> ANY state EXCEPT af (can't be "after fall" without falling)
//   f  (falling)     -> f, af only
//   af (after fall)  -> af, st, si only (recovery states)

static const bool VALID_TRANSITIONS[N_CLASSES][N_CLASSES] = {
    // To:    af     f      nf     r      si     st     w
    // From af (after fall): can go to af, si, st (recovery)
    {        true,  false, false, false, true,  true,  false },
    // From f (falling): can go to f, af only
    {        true,  true,  false, false, false, false, false },
    // From nf (unstable): can go to any EXCEPT af
    {        false, true,  true,  true,  true,  true,  true  },
    // From r (running): can go to any EXCEPT af
    {        false, true,  true,  true,  true,  true,  true  },
    // From si (sitting): can go to any EXCEPT af
    {        false, true,  true,  true,  true,  true,  true  },
    // From st (standing): can go to any EXCEPT af
    {        false, true,  true,  true,  true,  true,  true  },
    // From w (walking): can go to any EXCEPT af
    {        false, true,  true,  true,  true,  true,  true  },
};

// Check if transition from current state to next state is valid
static inline bool is_valid_transition(int current_state, int next_state) {
    if (current_state < 0 || current_state >= N_CLASSES) {
        // No current state (first prediction) - allow any
        return true;
    }
    if (next_state < 0 || next_state >= N_CLASSES) {
        return false;
    }
    return VALID_TRANSITIONS[current_state][next_state];
}

// Get the most likely valid next state given ML prediction and confidence
// Returns the valid state closest to the prediction, or current state if stuck
static inline int get_valid_next_state(int current_state, int ml_prediction, const float* class_probs) {
    // If transition is valid, use the ML prediction
    if (is_valid_transition(current_state, ml_prediction)) {
        return ml_prediction;
    }
    
    // If class probabilities are available, find best valid alternative
    if (class_probs != NULL) {
        int best_valid = current_state;  // Default: stay in current state
        float best_prob = 0.0f;
        
        for (int i = 0; i < N_CLASSES; i++) {
            if (is_valid_transition(current_state, i) && class_probs[i] > best_prob) {
                best_prob = class_probs[i];
                best_valid = i;
            }
        }
        return best_valid;
    }
    
    // No probabilities available - stay in current state
    return current_state;
}

#endif // LABELS_H
