/*
 * Feature definitions for IMU fall detection
 * Auto-generated by export_model_for_esp32.py
 */

#ifndef FEATURES_H
#define FEATURES_H

// Number of features
#define N_FEATURES 32

// Feature indices (for reference)
#define FEAT_AX_MEAN 0
#define FEAT_AX_STD 1
#define FEAT_AX_MIN 2
#define FEAT_AX_MAX 3
#define FEAT_AY_MEAN 4
#define FEAT_AY_STD 5
#define FEAT_AY_MIN 6
#define FEAT_AY_MAX 7
#define FEAT_AZ_MEAN 8
#define FEAT_AZ_STD 9
#define FEAT_AZ_MIN 10
#define FEAT_AZ_MAX 11
#define FEAT_A_MAG_MEAN 12
#define FEAT_A_MAG_STD 13
#define FEAT_A_MAG_MIN 14
#define FEAT_A_MAG_MAX 15
#define FEAT_GX_MEAN 16
#define FEAT_GX_STD 17
#define FEAT_GX_MIN 18
#define FEAT_GX_MAX 19
#define FEAT_GY_MEAN 20
#define FEAT_GY_STD 21
#define FEAT_GY_MIN 22
#define FEAT_GY_MAX 23
#define FEAT_GZ_MEAN 24
#define FEAT_GZ_STD 25
#define FEAT_GZ_MIN 26
#define FEAT_GZ_MAX 27
#define FEAT_W_MAG_MEAN 28
#define FEAT_W_MAG_STD 29
#define FEAT_W_MAG_MIN 30
#define FEAT_W_MAG_MAX 31

// Feature names (for debugging)
static const char* FEATURE_NAMES[N_FEATURES] = {
    "ax_mean",
    "ax_std",
    "ax_min",
    "ax_max",
    "ay_mean",
    "ay_std",
    "ay_min",
    "ay_max",
    "az_mean",
    "az_std",
    "az_min",
    "az_max",
    "a_mag_mean",
    "a_mag_std",
    "a_mag_min",
    "a_mag_max",
    "gx_mean",
    "gx_std",
    "gx_min",
    "gx_max",
    "gy_mean",
    "gy_std",
    "gy_min",
    "gy_max",
    "gz_mean",
    "gz_std",
    "gz_min",
    "gz_max",
    "w_mag_mean",
    "w_mag_std",
    "w_mag_min",
    "w_mag_max"
};

#endif // FEATURES_H
